fix: add missing semicolon between IIFEs in index.html
Fixes the TypeError '(intermediate value)(...) is not a function' by adding a semicolon between the two immediately invoked function expressions (IIFEs) in index.html. This resolves a JavaScript Automatic Semicolon Insertion (ASI) issue.